vich_uploader:
    db_driver: orm


    mappings:
        Uploaded_file:
            uri_prefix: /upload/file
            upload_destination: '%kernel.project_dir%/public/upload/file'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
